name: ci
on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

jobs:
  yaml-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
       node-version: 20

    - name: Imstall dependence
      run: cd tests && yarn install

    - name: Check yaml
      run: cd tests && node index.js

  sh-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lint: [shellcheck, shfmt]

    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: sudo apt update && sudo apt install -y ${{ matrix.lint }}
      - name: lint
        run: |
          if [ ${{ matrix.lint }} = "shfmt" ]; then
              shfmt -w -i 2 ksupatch.sh
          else
              ${{ matrix.lint }} ksupatch.sh
          fi

  ci-test:
    strategy:
      fail-fast: false
    needs:
      - yaml-check
      - sh-check
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Test CI
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/crdroidandroid/android_kernel_xiaomi_sdm660
          kernel-dir: lavender-12
          branch: 12.1
          config: lavender_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          ksu-lkm: true
          android-version: 12.1
          aosp-clang-version: r487747c
          python-27: true
          disable-lto: true
          overlayfs: true
          lxc: false
          lxc-patch: false
          anykernel3: false
